# TRABAJO PRÁCTICO 3
## Julián Santos (Comisión 4)


### Ejercicio 1: Slicing y Sub-matrices

In [7]:
import numpy as np

#1
matriz = np.arange(1, 26).reshape(5, 5)
print(matriz)

#2
subMatriz = matriz[1:4, 1:4]
print("\n", subMatriz)

#3
ultima_columna = matriz[:, -1]
print("\n", ultima_columna)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

 [ 5 10 15 20 25]


### Ejercicio 2: Estadísticas con Ejex (Axis)

In [17]:
import numpy as np

ventas = np.array([
    [1500, 2000, 1800, 2200],
    [1100, 1300, 1200, 1500],
    [3000, 3100, 2900, 3500]
])

#1 
total = np.sum(ventas)
print(total)

#2
promedio_semanal = np.mean(ventas, axis=0)
print("\n", promedio_semanal)

#3
max_por_sucursal = np.max(ventas, axis=1)
print("\n", max_por_sucursal)

25100

 [1866.66666667 2133.33333333 1966.66666667 2400.        ]

 [2200 1500 3500]


### Ejercicio 3: El poder de la Máscara Booleana

In [21]:
import numpy as np

#1
arr = np.arange(1, 21)
print(arr)

#2
mascara =  arr % 2 == 0
print("\n", mascara)

#3
pares = arr[mascara]
print("\n", pares)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

 [False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False  True]

 [ 2  4  6  8 10 12 14 16 18 20]


### Ejercicio 4: Condiciones Múltiples (El Analista de RRHH)

In [23]:
import numpy as np

edades = np.array([22, 55, 34, 19, 45, 61, 28, 30, 42])

#1
filtro = (edades >= 30) & (edades <= 50)
resultado = edades[filtro]

print(resultado)

#2
filtro_extremos = (edades < 25) | (edades > 55)
resultado_extremos = edades[filtro_extremos]

print("\n", resultado_extremos)


[34 45 30 42]

 [22 19 61]


### Ejercicio 5: Modificación Condicional

In [27]:
import numpy as np

#1
matriz = np.zeros((4, 4))
print(matriz)

#2
matriz[1:3, 1:3] = 9

#3
print("\n", matriz)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
 [0. 9. 9. 0.]
 [0. 9. 9. 0.]
 [0. 0. 0. 0.]]


### Ejercicio 6: Desafío Integrador "El Profesor Robot" 

In [42]:
import numpy as np

#1
calificaciones = np.random.randint(1, 11, 50)
print(calificaciones)

#2
promedio = np.mean(calificaciones)
print("\nPromedio:", promedio)

#3
desaprobados = calificaciones[calificaciones < 4]
print("\nNotas desaprobadas:", desaprobados)

cantidad_desaprobados = desaprobados.size
print("\nHay", cantidad_desaprobados, "desaprobados en total")

#4
calificaciones[calificaciones < 4] = 4

#5
print("\nNotas finales:", calificaciones)

[ 9  2  7  4  4  5  2  8  9  3  4  5  4  3  5  9  6  4  3  5  3  4  1  8
  3  2  9  2  4  6  2  7 10  6  9  7  1  4  9  9  9  8  1  4  3  1  6 10
  9  3]

Promedio: 5.22

Notas desaprobadas: [2 2 3 3 3 3 1 3 2 2 2 1 1 3 1 3]

Hay 16 desaprobados en total

Notas finales: [ 9  4  7  4  4  5  4  8  9  4  4  5  4  4  5  9  6  4  4  5  4  4  4  8
  4  4  9  4  4  6  4  7 10  6  9  7  4  4  9  9  9  8  4  4  4  4  6 10
  9  4]
