# TRABAJO PRÁCTICO 2
## Julián Santos (Comisión 4)




### Ejercicio 1: Creación y Atributos

In [3]:
import numpy as np

# 1
edades = np.array([22, 25, 30, 35, 40])
print ("Las edades son: ", edades, "\n")

# 2
print("Dimensiones (ndim): ", edades.ndim)
print("Forma (shape): ", edades.shape)
print("Tipo de dato (dtype): ", edades.dtype, "\n")

# 3
edades_float = edades.astype(np.float64)
print(edades_float)
print("Nuevo tipo de dato: ", edades_float.dtype)

Las edades son:  [22 25 30 35 40] 

Dimensiones (ndim):  1
Forma (shape):  (5,)
Tipo de dato (dtype):  int64 

[22. 25. 30. 35. 40.]
Nuevo tipo de dato:  float64


### Ejercicio 2: Secuencias Automáticas

In [ ]:
import numpy as np 

# 1
ids_clientes = np.arange(1, 101)
print(ids_clientes, "\n")

# 2
puntos_grafico = np.linspace(0, 10, 50)
print(puntos_grafico)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100] 

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.795

### Ejercicio 3: Matrices y Datos Aleatorios

In [1]:
import numpy as np 

# 1
matriz = np.random.rand(3, 4)
print (matriz, "\n")

# 2
matriz_unos = np.ones((3, 4))
print(matriz_unos)

[[0.69583603 0.51447666 0.97915573 0.0999507 ]
 [0.20613134 0.829742   0.37350502 0.15084404]
 [0.73218128 0.80673717 0.17916934 0.32222927]] 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Ejercicio 4: El Simulador de Inventario (Integración)

In [2]:
import numpy as np 

# 1
cant_sucur = input ("Ingrese la cantidad de sucursales: ")
cant_produ = input ("Ingrese la cantidad de productos: ")

# 2
cant_sucur = int(cant_sucur)
cant_produ = int(cant_produ)

# 3
inventario = np.zeros((cant_sucur, cant_produ))

# 4
print("Base de datos de inventario inicializada correctamente")
print(inventario)


Base de datos de inventario inicializada correctamente
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


### Ejercicio 5: Redimensionando la realidad (Reshape)

In [3]:
import numpy as np

# 1
vector = np.arange(1, 13)
print(vector, "\n")

# 2
matriz = vector.reshape(3, 4)
print(matriz, "\n")

# 3
print("Dimensiones: ", matriz.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

Dimensiones:  2


### Ejercicio 6: El peso de los datos (Optimización)

In [4]:
import numpy as np 

# 1
temper = np.array([25.5, 28.1, 22.4, 19.9, 30.2])
print(temper)
print("Tipo de dato: ", temper.dtype)

# 2
temper_int = temper.astype(np.int32)

# 3
print(temper_int)
print("Tipo de dato: ", temper_int.dtype)

[25.5 28.1 22.4 19.9 30.2]
Tipo de dato:  float64
[25 28 22 19 30]
Tipo de dato:  int32


### Ejercicio 7: Simulador de Dados (Números Aleatorios Enteros)

In [7]:
import numpy as np

# 1 
dado = np.random.randint(1, 7, size=10)

# 2
print(dado)

[2 1 1 5 3 1 5 3 1 1]


### Ejercicio 8: Limpieza de sensores (Conversión desde texto)

In [11]:
import numpy as np

# 1
import numpy as np

humedad_texto = np.array(["45.2", "48.1", "42.5", "50.0"])
print(humedad_texto)
print("Tipo de dato:", humedad_texto.dtype, "\n")

# 2
# print(humedad_texto.sum())

# 3
humedad_float = humedad_texto.astype(np.float64)

print(humedad_float)
print("Nuevo tipo de dato:", humedad_float.dtype)

['45.2' '48.1' '42.5' '50.0']
Tipo de dato: <U4 

[45.2 48.1 42.5 50. ]
Nuevo tipo de dato: float64


### Ejercicio 9: La Matriz Identidad y un pequeño "spoiler"

In [13]:
import numpy as np

# 1 y 2
matriz = np.eye(4)
print(matriz)
print("\n")

# 3
resultado = matriz * 5
print(resultado)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


[[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
